### ISSUE TITLE
Things To-Do

### ISSUE THREAD

**Issue by ec-student** [ec-student/multi-page#1]
- [ ] Find higher res images
- [ ] Add a Google web font
- [ ] Validate my CSS
